openapi: "3.0.2"
info:
  version: 3.2.0
  x-date: 17-06-2019
  x-status: defined
  title: Account
  description: |-

    To charge the use of resources accounting can be used. Accounting can be
    implemented on a variety of resources, such as users, groups or
    organizations. It is up to the implementer to provide rules and cost for
    it. If neededvvmultiple accounting resources can be implemented.

  termsOfService: "https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt"
  contact:
    name: NIST BDRA Interface Subgroup
  license:
    name: Apache 2.0
    url: https://github.com/cloudmesh/cloudmesh-nist/blob/master/LICENSE.txt
externalDocs:
  description: more infortion abut the NIST BDRA
  url: https://github.com/cloudmesh-community/nist/blob/master/docs/nistvol8-2.epub?raw=true
servers:
  - url: /cloudmesh/v3
paths:
  /account:
    get:
      tags:
        - Account
      summary: Returns a the accounts
      description: Returns the accounts
      operationId: cloudmesh.account.list
      responses:
        '200':
          description: The list of accounts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Account'
        '401':
          description: Not authorized
  /account/{name}:
    get:
      tags:
        - Account
      summary: Returns the named account
      description: Returns the named account
      operationId: cloudmesh.account.find_by_name
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
          description: The name of the account
      responses:
        '200':
          description: Returning the information of the account
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'
        '401':
          description: Not authorized
        '404':
           description: The named account could not be found
    put:
      tags:
        - Account
      summary: Set the value of a account
      description: Set the value of the named account
      operationId: cloudmesh.account.add
      requestBody:
        description: The account and its value
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Account'
      responses:
        '200':
          description: Account updated or created
        '400':
          description: Error updating account
        '401':
          description: Not authorized
    delete:
      tags:
        - Account
      summary: Deletes the named account
      description: Deletes a account by name
      operationId: cloudmesh.account.delete_by_name
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
          description: The name of the account
      responses:
        '200':
          description: Deletion successful
        '401':
          description: Not authorized
        '404':
           description: The named account could not be found
components:
  schemas:
    Account:
      type: object
      description: account information including finances and summary.
      properties:
        name:
          type: string
          description: name of account
          example: GroupAccount
        description:
          type: string
          description: the purpose of the account
          example: "Charging all users for the account access"
        charge:
          type: integer
          minimum: 0
          description: The current chare of the account
          example: 1
        unit:
           type: string
           description: the unit in which the account is charged and the charge value is stored
           example: SU