swagger: "2.0"
info:
  version: 3.1.0
  x-status: defined
  x-date: 29-01-2019
  title: Alias
  description: |-

    A user may be interested to create an alias for a resource. This
    is a name useful to the user. A User can deploy a service in which
    such aliasses are stored. The aliasses could naturally be shared
    with other users. A resource could have one or more aliasses.  The
    reason for an alias is that a resource may have a complex name but
    a user may want to refer to the resource using a name that is
    suitable for the user's application.

  termsOfService: 'https://github.com/cloudmesh-community/nist/blob/master/LICENSE.txt'
  contact:
    name: Cloudmesh RESTful Service Example
    url: https://cloudmesh-community.github.io/nist/spec/
  license:
    name: Apache
host: localhost:8080
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /cloudmesh/alias:
    get:
      description: Returns all aliases
      operationId: get_alias
      produces:
        - application/json
      responses:
        '200':
          description: alias information
          schema:
            $ref: '#/definitions/Alias'
    put:
      summary: Create a new alias
      description: Create a new alias      
      operationId: add_alias
      parameters:
        - in: body
          name: alias
          required: true
          description: The new alias to create
          schema:
            $ref: '#/definitions/Alias'
      responses:
        '201':
          description: Created
  '/cloudmesh/alias/{name}':
    get:
      summary: Returns an alias by name
      description: Returns an alias by name      
      operationId: get_alias_by_name
      parameters:
        - name: name
          in: path
          required: true
          type: string
          description: The name of the alias
      produces:
        - application/json
      responses:
        '200':
          description: alias info
          schema:
            $ref: '#/definitions/Alias'
definitions:
  Alias:
    type: object
    description: the alias
    properties:
      name:
        type: string
        description: The name of the alias
      origin:
        type: string
        description: The original object name
      timestamp:
        description: timestamps associated with the resource
        $ref: 'timestamp.yaml#/definitions/Timestamp'
