swagger: "2.0"
info:
  version: 3.0.2
  x-date: 10-30-2018
  title: key
  description: |-
  
    A service to store key, value, type information. All of them are
    stored as Strings.

    * TODO: assign for review and improvement
    
  termsOfService: https://github.com/cloudmesh-community/nist/blob/master/LICENSE.txt
  contact:
    name: Cloudmesh RESTful Service Example
    url: https://cloudmesh-community.github.io/nist
  license:
    name: Apache
host: localhost:8080
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /cloudmesh/keys:
    get:
      description: Returns all keys
      operationId: get_key
      produces:
        - application/json
      responses:
        200:
          description: key info
          schema:
            $ref: '#/definitions/Key'
    put:
      summary: Create a new key
      operationId: add_key
      parameters:
        - in: body
          name: key
          description: The new key to create
          schema:
            $ref: '#/definitions/Key'
      responses:
        201:
          description: Created
  '/cloudmesh/key/{name}':
    get:
      description: Returns a key
      operationId: get_key_by_name
      parameters:
        - name: name
          in: path
          required: true
          type: string
      produces:
        - application/json
      responses:
        200:
          description: key info
          schema:
            $ref: '#/definitions/Key'
definitions:
  Key:
    type: object
    description: the key
    properties:
      name:
        type: string
        description: name of the key
      value:
        type: string
        description: value of the key
      kind:
        type: string
        description: the key kind or type
      timestamp:
        description: timestamps associated with the resource
        $ref: 'timestamp.yaml#/definitions/Timestamp'
