swagger: "2.0"
info:
  version: 3.1.0
  x-date: 01-29-2019
  x-status: defined
  title: Image
  description: |-
  
    Image defines an object representing a system image
    in cloud that can be used to start virtual machines.

    Image objects are typically returned by the driver for the 
    cloud provider in response to the list_images function.
    
  termsOfService: 'https://github.com/cloudmesh-community/nist/blob/master/LICENSE.txt'
  contact:
    name: Cloudmesh RESTful Service Example
    url: https://cloudmesh-community.github.io/nist/spec/
  license:
    name: Apache
host: localhost:8080
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /cloudmesh/image:
    get:
      description: Returns all general description images
      operationId: get_image
      produces:
        - application/json
      responses:
        '200':
          description: default image info
          schema:
            $ref: '#/definitions/Image'
    put:
      description: Create a new image
      operationId: add_image
      parameters:
        - in: body
          name: image
          required: true
          description: The new image record to create
          schema:
            $ref: '#/definitions/Image'
      responses:
        '201':
          description: Created
  '/cloudmesh/image/{name}':
    get:
      description: Returns general description of an image
      operationId: get_image_by_name
      parameters:
        - name: name
          description: name of the image
          in: path
          required: true
          type: string
      produces:
        - application/json
      responses:
        '200':
          description: image info
          schema:
            $ref: '#/definitions/Image'
definitions:
  Image:
    type: object
    properties:
      id:
        type: string
        description: A unique id for the image
      name:
        type: string
        description: Name of the image
      label:
        type: string
        description: A label that can be defined by the user for the image
      description:
        type: string
        description: A description for the image
      collection:
        type: string
        description: The collection in which the image fits
      cloud:
        type: string
        description: A cloud provider for which the image is designed. If multiple are using the image, they are passed along as space seperated strings
      os_type:
        type: string
        description: The OS of the image
      osVersion:
        type: string
        description: The OS version of the image
      min_requirement:
        $ref: '#/definition/Minimum_Requirements'
        description: minimum requirement to run the image
      status:
        type: string
        description: The status of the image
      progress:
        type: integer
        description: The loading progress percentage of the image
      visibility:
        description: The visibility of the image                   
        type: string
      last_update:
        type: string
        format: date-time
        description: Date and time of the last update on the image
      timestamp:
        description: timestamps associated with the file
        $ref: 'timestamp.yaml#/definitions/Timestamp'

  Minimum_Requirements:
    type: object
    properties:
      disk_space:
        type: integer
        description: Minimum disk space in bytes required for the image
      ram:
        type: integer
        description: Minimum ram size in bytes to run the image
      cpu:
        type: string
        description: Minimum cpu required to run the image including number of cores and clock speed
