swagger: "2.0"
info:
  version: 3.1.0
  x-status: defined
  x-date: 01-29-2019  
  title: Key
  description: |-
  
    Many services and frameworks use Secure Shell (SSH) keys to
    authenticate. This service allows the convenient storage of the
    public key

  termsOfService: 'https://github.com/cloudmesh-community/nist/blob/master/LICENSE.txt'
  contact:
    name: Cloudmesh RESTful Service Example
    url: https://cloudmesh-community.github.io/nist
  license:
    name: Apache
host: localhost:8080
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /cloudmesh/key:
    get:
      description: Returns all keys
      operationId: get_key
      produces:
        - application/json
      responses:
        '200':
          description: key info
          schema:
            $ref: '#/definitions/Key'
    put:
      summary: Create a new key
      description: Create a new key      
      operationId: add_key
      parameters:
        - in: body
          name: key
          description: The new key to create
          schema:
            $ref: '#/definitions/Key'
      responses:
        '201':
          description: Created
  '/cloudmesh/key/{name}':
    get:
      description: Returns a key by name
      operationId: get_key_by_name
      parameters:
        - name: name
          in: path
          required: true
          type: string
          description: the name of the key
      produces:
        - application/json
      responses:
        '200':
          description: key info
          schema:
            $ref: '#/definitions/Key'
definitions:
  Key:
    type: object
    description: the key
    properties:
      name:
        type: string
        description: Name of the key
      description:
        type: string
        description: A description for the key
      fingerprint:
        type: string
        description: Key fingerprint
      publicKey:
        type: string
        description: Public key
      clouds:
        type: arrray
        items:
          type: string
        description: List of cloud providers on which the key works on
      nodes:
        type: arrray
        items:
          type: string
        description: List of nodes on which the key works on
      collection:
        type: string
        description: The collection in which the key fits in
      kind:
        type: string
        description: The key kind such as rsa, dsa
      timestamp:
        description: timestamps associated with the key
        $ref: 'timestamp.yaml#/definitions/Timestamp'

