openapi: "3.0.2"
info:
  version: 3.2.0
  x-date: 17-06-2019
  x-status: defined
  title: Secgroup
  description: |-
  
   A security group defines the incoming and outgoing security rules
   which can then be assigned to a node. The connection to and from the node
   will be determined by the security group rules, in addition to any other
   possible rules applied on network devices or from the instance's firewall
   settings. A security group may have one or multiple rules and a node may be
   associated with one or more security groups.
   
  termsOfService: "https://github.com/cloudmesh/cloudmesh-nist/blob/main/LICENSE.txt"
  contact:
    name: NIST BDRA Interface Subgroup
    url: https://cloudmesh-community.github.io/nist
  license:
    name: Apache 2.0
    url: https://github.com/cloudmesh/cloudmesh-nist/blob/main/LICENSE.txt
servers:
  - url: /cloudmesh/v3
paths:
  /secgroup:
    get:
      tags:
      - Security group
      summary: Returns all security groups
      description: Returns all security groups
      operationId: cloudmesh.secgroup.get
      responses:
        '200':
          description: security group information
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Secgroup"
        '401':
          description: Not authorized
  /secgroup/{name}:
    get:
      tags:
      - Security group
      summary: Return the security group by name
      description: Return the security group by name
      operationId: cloudmesh.secgroup.get_by_name
      parameters:
        - name: name
          description: name of the security group
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: security group information
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Secgroup"
        '401':
          description: Not authorized
        '404':
          description: The named security group could not be found
    post:
      tags:
      - Security group
      summary: Create the named security group
      description: Create a new named security group
      operationId: cloudmesh.secgroup.create
      parameters:
        - in: path
          name: name
          required: true
          description: The name of the security group to create
          schema:
            type: string
      responses:
        '201':
          description: Created
        '400':
          description: The group could not be created
        '401':
          description: Not authorized
  /secgroup/{name}/rule/{rule}:
    get:
      tags:
      - Security group
      summary: Get an existing rule from the specified security group
      description: Create a new rule in security group
      operationId: cloudmesh.secgroup.get_rule
      parameters:
        - in: path
          name: name
          required: true
          description: The named of the security group from which the rule will be deleted
          schema:
            type: string
        - in: path
          name: rule
          required: true
          description: The rule to be added
          schema:
            type: string
      responses:
        '200':
          description: The security group rule definition info
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/SecGroupRule"
        '401':
          description: Not authorized
        '404':
          description: The named security group or role could not be found
    put:
      tags:
      - Security group
      summary: Create or update specified security group
      description: Create a new rule in security group
      operationId: cloudmesh.secgroup.add_rule
      parameters:
        - in: path
          name: name
          required: true
          description: The name of the new security group to create
          schema:
            type: string
      requestBody:
        description: The new security group rule to create
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SecGroupRule'
      responses:
        '200':
          description: Created
        '401':
          description: Not authorized
        '404':
          description: The named security group or role could not be found
    delete:
      tags:
      - Security group
      summary: Delete an existing rule from the specified security group
      description: Create a new rule in security group
      operationId: cloudmesh.secgroup.delete_rule
      parameters:
        - in: path
          name: name
          required: true
          description: The named secgroup
          schema:
            type: string
        - in: path
          name: rule
          required: true
          description: The secgroup rule
          schema:
            type: string
      responses:
        '200':
          description: Deleted sucessfully
        '401':
          description: Not authorized
        '404':
          description: The named security group or role could not be found
components:
  schemas:
    Secgroup:
      type: object
      description: the security group object
      properties:
        name:
          type: string
          description: Name of the security group
        description:
          type: string
          description: Describes what the security group is for
        rules:
          type: array
          description: List of Security group rules
          items:
            $ref: "#/components/schemas/SecGroupRule"
    SecGroupRule:
      type: object
      description: security group rule
      properties:
        name:
          type: string
          description: Unique name of the rule
        ingress:
          type: boolean
          description: The defined security group rule is for ingress if True
        egress:
          type: boolean
          description: The defined security group rule is for egress if True
        remote_group:
          type: string
          description: Name of the group if the rule is defined by group
                       instead of IP range
        protocol:
          type: string
          description: The protocol used such as TCP, UDP, ICMP
          example: TCP
        from_port:
          type: integer
          description: Port range starting port
        to_port:
          type: integer
          description: Port range ending port
        cidr:
          type: string
          description: The source or destination network in CIDR notation,
          example: 129.79.0.0/16
