openapi: '3.0.2'
info:
  version: '3.1.1'
  x-status: TODO
  x-date: 02-15-2019
  title: Cloudmesh NIST BDRA Specification API
  description:
  termsOfService: 'https://github.com/cloudmesh-community/nist/blob/main/LICENSE.txt'
  contact:
    name: NIST BDRA Interface Subgroup
  license:
    name: Apache
host: localhost:8080
externalDocs:
  description: more infortion abut the NIST BDRA
  url: https://github.com/cloudmesh-community/nist/blob/main/docs/nistvol8-2.epub?raw=true
schemes:
  - http
